from enum import Enum
from pydantic import BaseModel


class ErrorCode(str, Enum):
    UPLOAD_FAILED = "UPLOAD_FAILED"
    UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE"
    TEXT_EXTRACTION_FAILED = "TEXT_EXTRACTION_FAILED"
    METADATA_VALIDATION_FAILED = "METADATA_VALIDATION_FAILED"
    EMBEDDING_FAILED = "EMBEDDING_FAILED"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    NEEDS_OCR = "NEEDS_OCR"
    RATE_LIMITED = "RATE_LIMITED"


class ApiError(BaseModel):
    code: ErrorCode
    message: str
